### PR TITLE
W-73 Change BG and colors navbar

### PR DESCRIPTION
**Pull request by Mariii-23**
# Description
The main goal of this PR is change the background and the colors of navbar. 
Here we fix some problems too. Please see for your self and if you find some problem tell me.

image
image
image
image

image
image

Also change the animation to 2s because 5seconds is to long.
And fix the footer for small screens:
image

## Issue
https://github.com/b1tsway/b1tsway.github.io/issues/73

## Type of change

Please delete options that are not relevant or select with a "x" the correct option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist(mark with a "x" the items you made):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I tested all related functionalities and I didn´t break anything

### CODE REVIEW

**Review by assebc — CHANGES_REQUESTED** [review]
in the home page, first section after hero, the right side text isn't align right so it looks weird

image

**Comment by Mariii-23** [comment]
> in the home page, first section after hero, the right side text isn't align right so it looks weird
> 
> image
Fix
image
image

**Comment by assebc** [comment]
> 

image
still the same

**Review by assebc — APPROVED** [review]
even though you changed in the wrong branch LGTM!

**Pull request merged**
